# Generated by Django 4.1.7 on 2023-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_country_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
