# Generated by Django 4.1.7 on 2023-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_user_is_activated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memetitle", models.CharField(max_length=255, unique=True)),
                ("memedetail", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
