# Generated by Django 4.1.7 on 2023-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_buzz_meme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.JSONField(default=list),
        ),
    ]
