# Generated by Django 4.1.7 on 2023-04-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_daily_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='id',
        ),
        migrations.AlterField(
            model_name='daily',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user'),
        ),
    ]
