# Generated by Django 4.1.7 on 2023-04-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_daily_id_alter_daily_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('date_until', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section', to_field='section_name')),
            ],
        ),
    ]
