# Generated by Django 4.1.7 on 2023-04-06 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_section_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyItem',
            fields=[
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('items', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('glasses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glasses', to='api.item')),
                ('hair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hair', to='api.item')),
                ('hat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hat', to='api.item')),
            ],
        ),
    ]
