# Generated by Django 4.1.7 on 2023-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_myitem_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myitem',
            name='items',
            field=models.JSONField(default=[]),
        ),
    ]
