# Generated by Django 4.1.7 on 2023-04-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_myitem_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myitem',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
